version: "3"

services:
  app:
    command: npm run dev
    stdin_open: true
    build: .
    tty: true
    ports:
      - "3000:3000"
      - '5555:5555'
    volumes:
      - ./:/app
      - /usr/src/app/node_modules

  db:
    image: 'postgres:12'
    env_file: .env
    platform: linux/arm64/v8
    ports:
      - '5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
